import "./globals.css";
import { Montserrat } from "next/font/google";
import "react-nice-dates/build/style.css";

const montserrat = Montserrat({
  subsets: ["cyrillic"],
  weight: ["100", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
